title:            Servant Tome
tagline:          Fix all the things.
description:      Security, risk, and freedom.
canonical: http://matteverson.github.io
host: 0.0.0.0

# Owner/author information
owner:
  name:           Matt Everson
  avatar:         avatar.png
  bio:            "Life-long technologist"
  email:          mattreverson@gmail.com
  twitter:        matteverson
  github:         matteverson
  #instagram:      ctrunsthis
  #dribbble:       coletownsend
  #disqus:         balzac
  #location:       "Buffalo, NY"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/matteverson/
    external: true
  - title: Matt Who?
    url: http://about.me/matteverson
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
markdown:    redcarpet

redcarpet:
    extensions: ['smart', 'strikethrough', 'filter_html']

# Github Pages enforces these no matter what. Including them here allows local
# testing
safe: true
lsi: false

# Github sets this but we are free to override it
highlighter: pygments

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

theme: jekyll-theme-hacker